apiVersion: apps/v1
kind: Deployment
metadata:
  name:  department-service-app
  namespace: default
  labels:
    app:  department-service-app
spec:
  selector:
    matchLabels:
      app: department-service-app
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  department-service-app
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  department-service-app
        image:  ashwin081288/department-service:0.0.1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        imagePullPolicy: Always
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env:
          - name: EUREKA_SERVER_ADDRESS
            valueFrom: 
              configMapKeyRef:
                name:  eureka-cm
                key: eureka_service_address
        ports:
        - containerPort:  9001
          name: dept-service
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
      restartPolicy: Always 

---

apiVersion: v1
kind: Service
metadata:
  name: department-service-svc
  namespace: default
spec:
  selector:
    app: department-service-app
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: department-service-app
    protocol: TCP
    port: 80
    targetPort: 9001
